// <auto-generated />
using System;
using ApiMunicipio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMunicipio.Migrations
{
    [DbContext(typeof(TallerContext))]
    [Migration("20260529033745_Datos añadidos")]
    partial class Datosañadidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMunicipio.Models.Taller", b =>
                {
                    b.Property<int>("IdTaller")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaller"));

                    b.Property<int>("CuposTaller")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionTaller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("NombreTaller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorTaller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTaller");

                    b.ToTable("Talleres");

                    b.HasData(
                        new
                        {
                            IdTaller = 1,
                            CuposTaller = 40,
                            DescripcionTaller = "Capacitación comunitaria",
                            FechaFin = new DateOnly(2026, 7, 30),
                            FechaInicio = new DateOnly(2026, 6, 1),
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(18, 0, 0),
                            NombreTaller = "Taller de Cocina",
                            SectorTaller = "Quitumbe"
                        },
                        new
                        {
                            IdTaller = 2,
                            CuposTaller = 40,
                            DescripcionTaller = "Capacitación comunitaria",
                            FechaFin = new DateOnly(2026, 12, 30),
                            FechaInicio = new DateOnly(2026, 7, 1),
                            HoraFin = new TimeOnly(12, 0, 0),
                            HoraInicio = new TimeOnly(10, 0, 0),
                            NombreTaller = "Taller de Baile",
                            SectorTaller = "Solanda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
