// <auto-generated />
using System;
using ApiMunicipio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiMunicipio.Migrations
{
    [DbContext(typeof(MunicipioContext))]
    partial class TallerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiMunicipio.Models.Feria", b =>
                {
                    b.Property<int>("IdFeria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFeria"));

                    b.Property<string>("DescripcionFeria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaFeria")
                        .HasColumnType("date");

                    b.Property<string>("NombreFeria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEmprendedores")
                        .HasColumnType("int");

                    b.Property<string>("SectorFeria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFeria");

                    b.ToTable("Ferias");
                });

            modelBuilder.Entity("ApiMunicipio.Models.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<string>("DescripcionReporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoReporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UbicacionReporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReporte");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("ApiMunicipio.Models.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("DescripcionSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoSolicitud")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSolicitud");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("ApiMunicipio.Models.Taller", b =>
                {
                    b.Property<int>("IdTaller")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaller"));

                    b.Property<int>("CuposTaller")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionTaller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("NombreTaller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectorTaller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTaller");

                    b.ToTable("Talleres");

                    b.HasData(
                        new
                        {
                            IdTaller = 1,
                            CuposTaller = 40,
                            DescripcionTaller = "Capacitación comunitaria",
                            FechaFin = new DateOnly(2026, 7, 30),
                            FechaInicio = new DateOnly(2026, 6, 1),
                            HoraFin = new TimeOnly(20, 0, 0),
                            HoraInicio = new TimeOnly(18, 0, 0),
                            NombreTaller = "Taller de Cocina",
                            SectorTaller = "Quitumbe"
                        },
                        new
                        {
                            IdTaller = 2,
                            CuposTaller = 40,
                            DescripcionTaller = "Capacitación comunitaria",
                            FechaFin = new DateOnly(2026, 12, 30),
                            FechaInicio = new DateOnly(2026, 7, 1),
                            HoraFin = new TimeOnly(12, 0, 0),
                            HoraInicio = new TimeOnly(10, 0, 0),
                            NombreTaller = "Taller de Baile",
                            SectorTaller = "Solanda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
